require:
  - code_scanning
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - Gemfile*
    - gemfiles/*
    - spec/fixtures/rails_app/**/*
    - vendor/bundle/**/*

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Naming/FileName:
  Exclude:
    - "lib/okcomputer-checks.rb"

Rails:
  Enabled: true

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - "spec/ok_computer/nexmo_check_spec.rb"


RSpec/VerifiedDoubleReference:
  Enabled: false
